### PR TITLE
Added a resource

### PR DESCRIPTION
**Pull request by CBID2**
I added a link to Rupali's repo. I'm going to add more links to other sources soon.

### CODE REVIEW

**Review by amandamartin-dev — CHANGES_REQUESTED** [review]
Amazing! Can you move this into the repositories section?

**Comment by CBID2** [comment]
> Amazing! Can you move this into the repositories section?

Sure! 😄

**Comment by CBID2** [comment]
> Amazing! Can you move this into the repositories section?

Done @amandamartin-dev! 😄

**Review by amandamartin-dev — APPROVED** [review]
Perfect! Thanks!

**Pull request merged**
